### ISSUE TITLE
Where did all these files come from?

### ISSUE THREAD

**Issue by adamvoss** [macchina/arduino-boards-sam#3]
Where did the files in this repository come from?

This is important on two fronts:
 - whether there is any attribution we need to provide.
 - consideration when specifying a license for this repository. (Ex. was was anything GPL licensed)

**Comment by macchina** [comment]
Files came from this repo here: 

https://github.com/arduino/ArduinoCore-sam

Perhaps it would have been better to fork from original repo to be able to capture any changes from original?

**Comment by adamvoss** [comment]
> Perhaps it would have been better to fork from original repo to be able to capture any changes from original?

Probably.  I admittedly do not know much about Arduino at the moment, but looking at what did change, I am inclined to agree that there may be value in keeping the relationship between the repositories so upstream changes can be captured here.

If you would like, I can use git to make this repository look like it was forked from there and then can contact GitHub Support to see if they can add the fork relationship (alternative would be to delete and recreate this repository).

**Comment by macchina** [comment]
Agreed, and please do! If support can't/won't add fork relationship, a delete/recreate sounds perfectly acceptable to me. Thank you, Adam!

**Comment by morganrallen** [comment]
I think fork is the best option.

- We will get upstream changes
- We can push back important fixes
- We can eventually have Macchina as a variant in that repo, making this obsolete.

**Comment by adamvoss** [comment]
> I think fork is the best option.
>
>  -  We will get upstream changes
>  -  We can push back important fixes
>  -  We can eventually have Macchina as a variant in that repo, making this obsolete.

If the above are realistic goals (and it would be great if they are), we will need a slightly different approach to be able to ensure we can merge with upstream.  Lets get this configured as a fork first, then I can worry bout those details, I will be able to make it work by having two branches in this repo, but a chance exists we will decide we want two repositories.

**Comment by adamvoss** [comment]
History has been re-written.  It took a little sleuthing to figure out where in the history of **ArduinoCore-sam** this repository should start.  I just kept trying farther back in history until the number of changed files (between the first commit that was here and the new parent) started increasing, then died a manual inspection as a sanity check. 99dfb82e44d5fe95f85d3b2c7161549219caeff4 now shows exactly what was changed to provide the initial support.  ~~There is also an `upstreamable` branch where any code changes should go before merging into `master` (will document in README).  That way once this is in a state it can be merged into the upstream repository, that can be done without carrying over things like our README and CI solution.~~ Edit: change my mind because I realized that given the loose coordination between the two projects merging to upstream will not be practical, cherry-picking will be the way to go.

I also reverted some changes that were only line ending changes from Dos/Windows (CRLF) to Unix (LF).  I don't disagree with the change, but that would be a better change to make upstream (and I don't think the change was intentional here).

The request to support regarding the forking relationship has been sent.

**Comment by adamvoss** [comment]
> If support can't/won't add fork relationship, a delete/recreate sounds perfectly acceptable to me.

This is not something they can do after the fact, so please delete this repository and fork **ArduinoCore-sam**.  They also informed me that, even if they could add the fork relationship, they would only do so if one of the repository owners contacts them directly.

**Comment by adamvoss** [comment]
> This is not something they can do after the fact, so please delete this repository and fork ArduinoCore-sam. They also informed me that, even if they could add the fork relationship, they would only do so if one of the repository owners contacts them directly.

@macchina Hold off on that.  I was focused on solving the problem I offered to help with, which was setting up CI/CD (Continuous Integration/Continuous Deployment) functionality for the repository as is.  While I could achieve that relatively easily with the things said previously, I have also concerned myself with manageability.   As I have learned more about how this piece fits into the overall Arduino puzzle, I am not convinced that the current approach is the best one.  I have [opened a thread on the Macchina forum](https://forum.macchina.cc/t/how-is-the-m2-processer-board-different-from-an-arduino-due/221?u=adamvoss) to try to get more information with regard to what we should be releasing.  The short of it is that this has forked and is releasing a whole Arduino Core, but my suspicion is that we really should only be publishing a variant that utilizes the existing SAM core.

**Comment by adamvoss** [comment]
Repository has been rewritten again and history should be stable now.  History of externally sourced files has been preserved.  Details can be found in [CONTRIBUTING.md](https://github.com/macchina/Macchina_Arduino_Boards/blob/master/CONTRIBUTING.md).
