### ISSUE TITLE
Which libraries should be included with the board configuration?

### ISSUE THREAD

**Issue by adamvoss** [macchina/arduino-boards-sam#30]
Referencing the [Macchina Community Showcase's list of libraries](http://showcase.macchina.cc/libraries.html), which should be included with the board configuration so users do not need to download them separately?

/cc @rocketjosh

**Comment by adamvoss** [comment]
@rocketjosh I'm inclined to include all the libraries that M2RET depends on.  Do you have any thoughts?

**Comment by rocketjosh** [comment]
Yes, I agree - A lot of people are going to want to use M2RET and by including all the libraries, it makes it a lot easier for everyone to get rolling.

**Comment by adamvoss** [comment]
Resolved by #32
