### ISSUE TITLE
Unused Library?

### ISSUE THREAD

**Issue by csBlueChip** [macchina/arduino-boards-sam#35]
The SAM does NOT have an MCP2515
But if you look in https://github.com/macchina/arduino-boards-sam/tree/master/sam/libraries
...you will notice the inclusion of the MCP2515 library
I guess this was relevant for the original ATMega2560 based Macchina, and was accidentally carried over when the new SAM/M2 devkit was created.

Should this dependency be completely removed from the SAM/Macchina2 dev kit?

**Comment by adamvoss** [comment]
Thanks for the question!  There is an MCP2515 on the [interface board](https://www.macchina.cc/content/interface-board-utd) that is used to provide [single-wire CAN](http://docs.macchina.cc/m2/technical-references/interfaces.html#single-wire-can).
